package nu.hex.mediatype;

/**
 *
 * DO NOT MODIFY! This interface is autogenerated.
 *
 * Changes done here will be owerwritten the next time the project runs.
 *
 * To add mediatypes or edit them, run this project and use the editor.
 *
 * If the MTD is manually edited, run the project and use the update button.
 *
 * To remove a mediatype, remove it manually from the MTD file.
 *
 */
public interface HexMediaType {

    /**
     * Kapmanj-format<br>
     *
     * XML-format för RPG-kampanjdata.<br>
     *
     * <br>
     * MediaType: <i>application/vnd.nu.hex.campaign-format.smrx+xml</i>
     * <br>
     * FileSuffix: <i>.smrx</i>
     */
    public static final String APPLICATION_VND_NU_HEX_CAMPAIGN_FORMAT_SMRX_XML = "application/vnd.nu.hex.campaign-format.smrx+xml";
    /**
     * Bokdokument-format<br>
     *
     * Standardiserat text format för att beskriva böcker.<br>
     *
     * <br>
     * MediaType: <i>application/vnd.nu.hex.location-format.srb</i>
     * <br>
     * FileSuffix: <i>.srb</i>
     */
    public static final String APPLICATION_VND_NU_HEX_LOCATION_FORMAT_SRB = "application/vnd.nu.hex.location-format.srb";
    /**
     * Platsdokument-format<br>
     *
     * Standardiserat text format för att beskriva platser.<br>
     *
     * <br>
     * MediaType: <i>application/vnd.nu.hex.location-format.srl</i>
     * <br>
     * FileSuffix: <i>.srl</i>
     */
    public static final String APPLICATION_VND_NU_HEX_LOCATION_FORMAT_SRL = "application/vnd.nu.hex.location-format.srl";
    /**
     * Bokdokument i HTML-format<br>
     *
     * <br>
     * MediaType: <i>text/vnd.nu.hex.location-format+html.srb</i>
     * <br>
     * FileSuffix: <i>.hsrb</i>
     */
    public static final String TEXT_VND_NU_HEX_LOCATION_FORMAT_HTML_SRB = "text/vnd.nu.hex.location-format+html.srb";
    /**
     * Platsdokument i HTML-format<br>
     *
     * <br>
     * MediaType: <i>text/vnd.nu.hex.location-format+html.srl</i>
     * <br>
     * FileSuffix: <i>.hsrl</i>
     */
    public static final String TEXT_VND_NU_HEX_LOCATION_FORMAT_HTML_SRL = "text/vnd.nu.hex.location-format+html.srl";
}
